name: Deploy React to EC2 for Multiple Domains

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd kushal-finance-frontend
            sudo git pull https://dusksoni:GITHUB_PAT_REMOVED@github.com/dusksoni/kushal-finance-frontend.git main
            sudo npm install -f
            sudo chmod -R 777 node_modules
            # ===== DOMAIN1.COM =======
            cp ~/envs/kushalfinance.env .env
            sudo npm run build
            sudo rm -rf /var/www/html/builds/kushal-finance/*
            sudo mv dist/* /var/www/html/builds/kushal-finance