steps:
  - name: SSH and Deploy
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.EC2_IP }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd ~/kushal-finance-backend

        # Pull latest changes
        git pull origin main

        # Install dependencies
        npm install -f

        # ========= API1.COM Setup =========

        # Set .env from central env location
        cp ~/backend-envs/kushalfinance.env .env

        # Run Prisma Migrations and Seeding
        npx prisma migrate deploy
        npx prisma db seed

        # Restart service with PM2
        pm2 delete api1 || true
        PORT=3001 pm2 start index.js --name api1

        # ========= Add more domains if needed =========
        # cp ~/backend-envs/another.env .env
        # npx prisma migrate deploy
        # npx prisma db seed
        # pm2 delete api2 || true
        # PORT=4002 pm2 start index.js --name api2

        # Save PM2 process list
        pm2 save
