name: Deploy Node App for Multiple Domains

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/node-app
            git pull origin main
            npm install

            # ===== API1.COM =====
            cp ~/envs/api1.env
            # ===== API1.COM =====
            cp ~/envs/api1.env .env
            pm2 delete api1 || true
            PORT=4001 pm2 start index.js --name api1 --log ~/logs/api1.log

            # ===== API2.COM =====
            cp ~/envs/api2.env .env
            pm2 delete api2 || true
            PORT=4002 pm2 start index.js --name api2 --log ~/logs/api2.log

            pm2 save
