name: Deploy Node App for Multiple Domains

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/kushal-finance-backend
            sudo git pull https://dusksoni:GITHUB_PAT_REMOVED@github.com/dusksoni/kushal-finance-backend.git main
            sudo npm install -f


            # ===== API1.COM =====
    
            # sudo cp ~/backend-envs/kushalfinance.env .env
            sudo npx prisma migrate deploy
            sudo npx prisma db seed
            sudo pm2 delete kushalfinance || true
            # sudo PORT=3001 pm2 start server.js --name kushalfinance
            sudo dotenv -e ~/backend-envs/kushalfinance.env -- pm2 start server.js --name kushalfinance

             # ===== API1.COM =====
    
            # sudo cp ~/backend-envs/test.env .env
            sudo npx prisma migrate deploy
            sudo npx prisma db seed
            sudo pm2 delete kushalfinanceStaging || true
            # sudo PORT=3001 pm2 start server.js --name kushalfinanceStaging
            sudo dotenv -e ~/backend-envs/test.env -- pm2 start server.js --name kushalfinanceStaging
            pm2 save